#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM 185
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_DELAY 20
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 30
#define COMBO_COUNT 12
#define COMBO_TERM 25
