#pragma once

#define ADAPTIVE_TERM 1200
#define COMBO_COUNT 25
#define COMBO_STRICT_TIMER
#define COMBO_TERM 48
#define IGNORE_MOD_TAP_INTERRUPT
#define MOUSEKEY_DELAY 20
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_TIME_TO_MAX 30
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define ONESHOT_TIMEOUT 800
#define TAPPING_FORCE_HOLD_PER_KEY
#define TAPPING_TERM 185
#define TAPPING_TERM_PER_KEY
// #define UNICODE_SELECTED_MODES UC_WIN, UC_LNX, UC_MAC

