SRC += muse.c

BOOTMAGIC_ENABLE   = no
COMBO_ENABLE       = yes
CONSOLE_ENABLE     = no
LEADER_ENABLE      = no
MOUSEKEY_ENABLE    = no
RGBLIGHT_ENABLE    = yes
TAP_DANCE_ENABLE   = no
UNICODE_ENABLE     = no
VIA_ENABLE         = no
